"""empty message

Revision ID: 622c6bfd5d09
Revises: df4165d00fb5
Create Date: 2024-09-27 12:08:44.321155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622c6bfd5d09'
down_revision: Union[str, None] = 'df4165d00fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'deleted')
    op.drop_column('post', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('comment', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
